name: trip_planner
description: "A comprehensive trip planning application designed to help travelers organize itineraries, visualize schedules, and track important details like Schengen zone days."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  google_fonts: ^7.0.2
  http: ^1.1.0
  intl: ^0.20.2
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
