name: trip_planner
description: "A comprehensive trip planning application designed to help travelers organize itineraries, visualize schedules, and track important details like Schengen zone days."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.2
  intl: ^0.20.2
  dio: ^5.9.0
  package_info_plus: ^8.0.0
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  http: ^1.6.0
  provider: ^6.1.5+1
  window_manager: ^0.5.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  url_launcher: ^6.3.1
  
  # Firebase                                                                                                                                                                                  
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.3
  firebase_crashlytics: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
